"""First migration

Revision ID: 88b167777436
Revises: 
Create Date: 2023-06-19 18:26:22.845371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88b167777436'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salary',
    sa.Column('salary', sa.Integer(), nullable=True),
    sa.Column('date_of_raising', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('salary')
    # ### end Alembic commands ###
